# Pytorch basic

In [24]:
import torch
a = torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

b = torch.tensor([1,2, 3.1, 4])
print(b.dtype) # 하나라도 실수면 자동으로 실수타입으로 변경

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32


In [25]:
A = torch.tensor([ [1, 2, 3], [3, 4, 5]])
#A = torch.tensor([[1,2], [3,4,5]]) # tensor는 행렬이기 때문에 각 행에 해당하는 숫자의 개수가 같아야 한다.
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [26]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3, 10, 2)) # tensor를 range 형태로 만든다.
print(torch.arange(0, 1, 0.1)) # 소수점도 가능하다.
print(torch.linspace(0, 1, 10)) # 0 에서부터 1포함 10개의 원소

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [27]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)
print(a - b)
print(a * b) # 성분끼리의 곱 ( Hadamard product )
print(a / b) # 성분끼리의 나누기
print(a**2)  # 성분에 대해서 제곱

A = torch.tensor([[1,2], [3,4]])
B = torch.tensor([[4,5], [6,7]])
print(A@B) # 행렬 곱

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([1, 4, 9])
tensor([[16, 19],
        [36, 43]])


# 인덱싱, 슬라이스

In [28]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[[-1]])
print(a[1:4])
print(a[5:])
print(a[:5])
print(a[:])

tensor(1)
tensor([9])
tensor([2, 3, 4])
tensor([6, 7, 8, 9])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
# 행렬에 대한 인덱싱과 슬라이싱
A = torch.tensor([ [1,2,3], [4,5,6], [7,8,9] ])
print(A[0])
print(A[-1])
print(A[1:])
print(A[0][2])
print(A[0,2]) # 리스트와 달리 이런식으로 표현 가능

print(A[1, :])
print(A[1, 0:3:2])
print(A[:,2]) # 전부, 2열
print(A[:][2]) # 위와 다름

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [30]:
# boolean 인덱싱
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,1]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[[True,True,False,False]]) # type을 tensor가 아닌 list로 넣어도 사용 가능하다.

c=[1,2,3,4]
# c[[True,True,False,False]] # list는 안된다!

tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([2, 8])
tensor([1, 2])


In [31]:
# tensor로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor를 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [32]:
# 총 정리
A=torch.tensor([[1,2],[3,4],[5,2],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 tensor형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,True], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])

tensor([[1, 2],
        [3, 4],
        [5, 2],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2, 2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 2],
        [5, 2],
        [5, 2]])


# pytorch의 여러 함수들

In [33]:
# 랜덤 분포 생성
A=torch.randn(3,3) # normal 의 n 평균 0, 분산 1
A=torch.randn(3,3) + 10 # 10을 더하면 평균 10
A=torch.randn(3,3) * 10 # 10을 곱하면 분산 100
B=torch.rand(3,3) # 이건 uniform ( 0 ~ 1 )
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[ 11.1027, -19.0833,  -3.5942],
        [ -7.4747,  -3.9390,  -1.8900],
        [ -2.7743,   6.9462,  -8.7538]])
tensor([[0.3705, 0.9674, 0.5167],
        [0.1153, 0.4281, 0.6631],
        [0.5651, 0.0093, 0.2733]])
tensor([[-7.4747, -3.9390, -1.8900],
        [-2.7743,  6.9462, -8.7538]])


In [34]:
# 절대값, exp, log, round
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A, decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[ 0.1926, -2.4143, -1.0133],
        [ 0.4519, -1.4488, -1.0616],
        [ 0.5549, -0.8054,  1.0183]])
tensor([[0.1926, 2.4143, 1.0133],
        [0.4519, 1.4488, 1.0616],
        [0.5549, 0.8054, 1.0183]])
tensor([[0.4389, 1.5538, 1.0066],
        [0.6723, 1.2037, 1.0303],
        [0.7449, 0.8975, 1.0091]])
tensor([[1.2124, 0.0894, 0.3630],
        [1.5714, 0.2349, 0.3459],
        [1.7417, 0.4469, 2.7686]])
tensor([[-1.6471,  0.8814,  0.0132],
        [-0.7942,  0.3707,  0.0598],
        [-0.5890, -0.2164,  0.0182]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[ 0., -2., -1.],
        [ 0., -1., -1.],
        [ 1., -1.,  1.]])
tensor([[ 0.1900, -2.4100, -1.0100],
        [ 0.4500, -1.4500, -1.0600],
        [ 0.5500, -0.8100,  1.0200]])
tensor([[ 0., -3., -2.],
        [ 0., -2., -2.],
        [ 0., -1.,  1.]])
tensor([[ 1., -2., -1.],
        [ 1., -1., -1.],
        [ 1., -0.,  2.]])


In [35]:
# sin, cos, tan
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi) <- float임 만약 tensor와 연산하면 tensor로 바꿔줌
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


In [36]:
# nan, inf
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [37]:
# max, min, argmax
A=torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0))
print(torch.max(A,dim=1)) # 1D array로 바꿔버림
print(torch.max(A, dim=0, keepdims=True))
print(torch.max(A, dim=1, keepdims=True)) # keepdims는 dimention을 유지 하는 것.
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A))
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[-0.5485, -0.3829, -0.9457,  0.0829],
        [-1.3040,  0.2108,  0.7495, -0.1987],
        [ 0.3626,  0.1787,  0.0372, -1.0677]])
tensor(0.7495)
torch.return_types.max(
values=tensor([0.3626, 0.2108, 0.7495, 0.0829]),
indices=tensor([2, 1, 1, 0]))
torch.return_types.max(
values=tensor([0.0829, 0.7495, 0.3626]),
indices=tensor([3, 2, 0]))
torch.return_types.max(
values=tensor([[0.3626, 0.2108, 0.7495, 0.0829]]),
indices=tensor([[2, 1, 1, 0]]))
torch.return_types.max(
values=tensor([[0.0829],
        [0.7495],
        [0.3626]]),
indices=tensor([[3],
        [2],
        [0]]))
tensor(-1.3040)
torch.return_types.min(
values=tensor([-1.3040, -0.3829, -0.9457, -1.0677]),
indices=tensor([1, 0, 0, 2]))
torch.return_types.min(
values=tensor([-0.9457, -1.3040, -1.0677]),
indices=tensor([2, 0, 3]))
tensor(6)
tensor([2, 1, 1, 0])
tensor([3, 2, 0])


In [38]:
# sort
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0)
print(a_sorted)

a=torch.randn(6,1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True)) # 내림차순

# 둘 다 같음. 보통 매서드 사용(오른쪽)
# torch.sort(a) == a.sort()
# torch.max(a) == a.max()
# torch.abs(a) == a.abs()

tensor([[ 0.0856],
        [-1.2538],
        [ 0.0130],
        [-2.6055],
        [-1.5439],
        [-0.4198]])
torch.return_types.sort(
values=tensor([[-2.6055],
        [-1.5439],
        [-1.2538],
        [-0.4198],
        [ 0.0130],
        [ 0.0856]]),
indices=tensor([[3],
        [4],
        [1],
        [5],
        [2],
        [0]]))
tensor([[-0.7339],
        [-0.4458],
        [ 0.4742],
        [-0.1685],
        [ 0.0583],
        [-0.7659]])
torch.return_types.sort(
values=tensor([[-0.7659],
        [-0.7339],
        [-0.4458],
        [-0.1685],
        [ 0.0583],
        [ 0.4742]]),
indices=tensor([[5],
        [0],
        [1],
        [3],
        [4],
        [2]]))
torch.return_types.sort(
values=tensor([[ 0.4742],
        [ 0.0583],
        [-0.1685],
        [-0.4458],
        [-0.7339],
        [-0.7659]]),
indices=tensor([[2],
        [4],
        [3],
        [1],
        [0],
        [5]]))


In [39]:
# sum, mean
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[ 1.3330, -0.7661,  0.3326, -0.1302],
        [ 1.5190,  0.6015, -1.1232,  0.3735],
        [ 0.9817,  1.1988, -0.8157, -0.1156]])
tensor(3.3894)
tensor([0.7693, 1.3708, 1.2493])
tensor([[0.7693],
        [1.3708],
        [1.2493]])
tensor(0.2825)
tensor([0.1923, 0.3427, 0.3123])
tensor([[0.1923],
        [0.3427],
        [0.3123]])
tensor(0.8885)
tensor([[0.7693],
        [1.3708],
        [1.2493]])
tensor([[0.1923],
        [0.3427],
        [0.3123]])
tensor(0.8885)


In [40]:
# reshape

A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

A=torch.randint(1,9,size=(3,3,2))
print(A)
print(A.shape)

B=A.reshape(3,2,3)
print(B)
print(B.ndim)

tensor([1, 4, 4, 1, 2, 1, 1, 4, 4, 3, 3, 4])
torch.Size([12])
tensor([[[1, 4, 4],
         [1, 2, 1]],

        [[1, 4, 4],
         [3, 3, 4]]])
3
tensor([[[3, 3],
         [2, 2],
         [5, 2]],

        [[5, 4],
         [5, 7],
         [3, 4]],

        [[8, 2],
         [1, 1],
         [6, 2]]])
torch.Size([3, 3, 2])
tensor([[[3, 3, 2],
         [2, 5, 2]],

        [[5, 4, 5],
         [7, 3, 4]],

        [[8, 2, 1],
         [1, 6, 2]]])
3


In [42]:
# reshape -1 사용
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [41]:
# transpose, permute
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)
print(a.t()@b)

A=torch.randn(2,3,4)
print(A)
print(A.permute(0,2,1).shape) # permute는 해당 shape에 기존의 몇번째 shape로 바꾸는 것
print(A.permute(0,2,1))
print(A.transpose(0,2).shape) # transpose 는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[[-1.2441,  0.1862,  0.0333,  0.7996],
         [ 0.7654, -0.7226,  1.8897, -0.1064],
         [ 0.6723, -0.0767,  0.9746,  1.0103]],

        [[-1.2051,  0.0079,  0.6273, -0.7547],
         [-0.8607, -0.9943,  0.4706,  0.0671],
         [ 1.3269, -1.3593, -0.0375,  0.1956]]])
torch.Size([2, 4, 3])
tensor([[[-1.2441,  0.7654,  0.6723],
         [ 0.1862, -0.7226, -0.0767],
         [ 0.0333,  1.8897,  0.9746],
         [ 0.7996, -0.1064,  1.0103]],

        [[-1.2051, -0.8607,  1.3269],
         [ 0.0079, -0.9943, -1.3593],
         [ 0.6273,  0.4706, -0.0375],
         [-0.7547,  0.0671,  0.1956]]])
torch.Size([4, 3, 2])


In [43]:
# ...의 사용
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [44]:
# cat
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))

C=torch.vstack([A,B]) # dim = 0 에 대해서 사용. 헷갈리니깐 사용 x
D=torch.hstack([A,B]) # dim = 1 에 대해서 사용. 헷갈리니깐 사용 x

E=torch.cat([A,B], dim = 0)
F=torch.cat([A,B], dim = 1)
G=torch.cat([A,B], dim = 2)

print(C.shape)
print(D.shape)
print(E.shape)
print(F.shape)
print(G.shape)

torch.Size([4, 3, 4])
torch.Size([2, 6, 4])
torch.Size([4, 3, 4])
torch.Size([2, 6, 4])
torch.Size([2, 3, 8])


In [45]:
# squeeze
A = torch.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape) # 1 짜리를 쥐어짜내서 없애줌

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [46]:
# unsqueeze
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)
# unsqueeze, reshape 둘 다 숫자가 들어가는 배열도 같음.

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [47]:
# unsqueeze 활용
A = torch.ones(3,4)
B = torch.zeros(3,4)
# A와 B를 (2, 3, 4) 로 쌓고 싶다. 근데 여기서 바로 cat을 할 순 없다. (6,4) 또는 (3,8)만됨

A = A.unsqueeze(dim=0)
B = B.unsqueeze(dim=0)
C = torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [48]:
# 복사
A = torch.tensor([[1,2], [3,4]])
B = A # 주소까지 같이 복사하기 때문에 값이 바뀐다.
B[0,0] = 100

print(B)
print(A)

A = torch.tensor([[1,2], [3,4]])
C = A.clone()
C[0,0] = 500
print(C)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[100,   2],
        [  3,   4]])
tensor([[500,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


# @에 대해 추가내용

In [49]:
A = torch.randn(5,7)
B = torch.randn(7,10)
C = A@B
print(C.shape)

A = torch.randn(32,5,7) # 3차원 행렬곱을 하는게 아니라 각 채널마다 행렬곱을 해준다.
B = torch.randn(32,7,10)
C = A@B
print(C.shape) # 총 32번의 행렬곱을 하는 것.

torch.Size([5, 10])
torch.Size([32, 5, 10])


# repeat

In [50]:
A = torch.rand(2,3)
A_repeat = A.repeat(3,1,3,2)
print(A)
print(A_repeat.shape)
print(A_repeat)

tensor([[0.7417, 0.1794, 0.9483],
        [0.6836, 0.5987, 0.2655]])
torch.Size([3, 1, 6, 6])
tensor([[[[0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655],
          [0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655],
          [0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655]]],


        [[[0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655],
          [0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655],
          [0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655]]],


        [[[0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483],
          [0.6836, 0.5987, 0.2655, 0.6836, 0.5987, 0.2655],
          [0.7417, 0.1794, 0.9483, 0.7417, 0.1794, 0.9483]

# numpy <-> torch

In [51]:
import numpy as np
import torch

a = np.array([1,2,3])
b = torch.tensor([1,2,3])

A = torch.tensor(a) # A = torch.from_numpy(a)
print(type(A))

B = b.numpy() # B = np.array(b)
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


# 딥러닝을 가능케한 autograd

In [52]:
# tensor엔 requires_grad 속성이 있다.
a = torch.tensor([1.])
print(a)
a.requires_grad=True
print(a)
print(a.requires_grad)

#x = torch.tensor([1], requires_grad=True) # 정수로는 미분이 안되서 오류
x = torch.tensor([1.], requires_grad=True) # 1. == 1.0
print(x)

tensor([1.])
tensor([1.], requires_grad=True)
True
tensor([1.], requires_grad=True)


In [53]:
# 텐서 연산시 grad_fn이 붙는다.
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y) # PowBackward0 가 붙어있다.

print(x.grad)
y.backward() # 미분해주는 것
print(x.grad) # 미분 후 x를 기입한 값을 x.grad에 넣어둔다.

# 1. numerical(수치적)으로 bacword -> 순간변화율을 이용해서 미분 y2 = (x+10^-12)^2
# -> 정확하게 2는 안나올 거임.
# 2. closed form(도함수)를 가지고 있으면 거기에 x값을 기입하자. -> pytorch 방식

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [54]:
x = torch.tensor([1.], requires_grad=True)
y = x.argmax()
print(y) # 도함수가 없는 것에 대해서는 grad_fn이 없음

tensor(0)


In [55]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y) # PowBackward0 가 붙어있다
# y.retain_grad() # 이걸 하면 y.grad도 볼 수 있다.

z=3*y
print(z) # MulBackward0 가 붙어있다. ( 제일 마지막 연산 출력 )

z.backward() # dz/dx = dz/dy dy/dx  -> 체인룰로 진행하기 떄문에 backward, requires_grad=True인 아이들에 대해서 미분한다.
print(x.grad)
print(y.grad) # leaf Tensor가 아니다 라는 워닝이 뜸 -> requires_grad=True인 아이들이 leaf Tensor임

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])
None


<ipython-input-55-aecf02da4d37>:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)


In [56]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
z = 3*y

y.backward() # 이렇게하면 y에서부터 뒤로 넘어감
print(x.grad)

tensor([2.])


In [56]:
x = torch.tensor([1.], requires_grad=True)
a = x**2
print(a) # PowBackward0 가 붙어있다.
b = 3*a**2+1
print(b) # AddBackward0 가 붙어있다. # 마지막만 출력. 하지만 다 미분이 기입은 되어 있음.
b.backward()
print(x.grad)

In [56]:
x = torch.tensor([1.], requires_grad=True)
a = x**2
b = a+1
c = b**2
c.backward()

print(x.grad)

In [56]:
# 여러개의 변수가 있을 때 편미분
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([1.], requires_grad=True)
z = 2*x**2 + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)

In [ ]:
# 함수를 사용해도 똑같이 쌓아짐. x1, x2, x3에 대해서 각각 제곱 후 더한 것이기 때문에 미분하면 3개의 원소를 가진 그레디언트 값이 나옴
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(y)
print(x.grad) # 스칼라를 벡터로 미분

In [ ]:
# requres_grad를 없애줄 때 - 1
x = torch.tensor([1.], requires_grad=True)
x.requires_grad=False
# transfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

In [ ]:
# requres_grad를 없애줄 때 - 2
x = torch.tensor([1.], requires_grad=True)
x = x.detach() # detach도 많이 씀 -> requires_grad가 없어짐
print(x)
print(x.requires_grad)
y=x**2
print(y)

In [ ]:
# detach 와 torch.no_grad
x = torch.tensor([1.], requires_grad=True)

# chain rule을 위해 계속 grad_fn을 update 하니깐 grad_fn 잠시 안 계산하고 싶을 때 사용한다.
# 모델 테스트 시에 불필요하게 메모리를 쓸 필요가 없으니 사용한다.
with torch.no_grad(): # requires_grad는 바뀌지 않지만, grad_fn을 계산하지 않겠다.
    y=x**2
    # y.backward() ## error!
    print(x.requires_grad)
    print(y)
print(x.requires_grad)
y=x**2
y.backward()
print(y)